name: Deploy to Environment

on:
  # push:
  #   branches:
  #     - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy DB to'
        required: true
        default: 'DEMO'
        type: choice
        options:
          - ATAKER-PROD
          - DEMO
          - MUT-PROD

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push --include-seed --debug
      - run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
