name: Dump Translations
on:
  workflow_dispatch:

jobs:
  dump-translations-table:
    runs-on: [ "ubuntu-latest" ]
    env:
      PG_HOST: ${{ secrets.DEV_DB_HOSTNAME }}
      PG_PORT: 5432
      PG_USER: ${{ secrets.DEV_DB_USER }}
      PG_PWD: ${{ secrets.STAGING_DB_PASSWORD }}
      PG_DB: postgres


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Run SQL statement
        run: |
          psql -h ${{ env.PG_HOST }} -U ${{ env.PG_USER }} -d ${{ env.PG_DB }} -c "SELECT 'INSERT INTO translations (id, key, language, translation, context, created_at, updated_at) VALUES (''' || id || ''', ''' || key || ''', ''' || language || ''', ''' || translation || ''', ''' || COALESCE(context, 'NULL') || ''', ''' || created_at || ''', ''' || updated_at || ''') ON CONFLICT (id) DO UPDATE SET key = EXCLUDED.key, language = EXCLUDED.language, translation = EXCLUDED.translation, context = EXCLUDED.context, updated_at = EXCLUDED.updated_at' FROM translations" -t -o seed.sql
        env:
          PGPASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      - name: Rename and move SQL file
        run: |
          mv seed.sql supabase/seed.sql

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add .
          git commit -m "update translations table" || echo "No changes to commit"
          git push
